recaptcha {
    // These keys are generated by the ReCaptcha service
	publicKey = "6LfTZcwSAAAAAISkWiE7aqtH3xa7vdmu7GL9O7bm"
	privateKey = "6LfTZcwSAAAAAPI6fiz2iRkuG19QN3LYOlQVDhHS"

	// Include the noscript tags in the generated captcha
	includeNoScript = true
}

mailhide {
    // Generated by the Mailhide service
    publicKey  = "6LfYyfQSAAAAAHkWGU_iYOOpZAbny_JSPpH4wQhM"//publicKey = "6LfTZcwSAAAAAISkWiE7aqtH3xa7vdmu7GL9O7bm"
    privateKey = "6LfYyfQSAAAAAGSVOze777G1pjpKuOV0OGbk5VYu"//privateKey = "6LfTZcwSAAAAAPI6fiz2iRkuG19QN3LYOlQVDhHS"

}

environments {
  development {
    recaptcha {
      // Set to false to disable the display of captcha
      enabled = true

      // Communicate using HTTPS
      useSecureAPI = true
    }
  }
  production {
    recaptcha {
      // Set to false to disable the display of captcha
      enabled = true

      // Communicate using HTTPS
      useSecureAPI = true
    }
  }
}