recaptcha {
    // These keys are generated by the ReCaptcha service
    publicKey  = "6Lc6dPgSAAAAAPOwGa9-CmSE_HdprJ-ci5aflPWJ"
    privateKey = "6Lc6dPgSAAAAAJSUxs8xxqmO-KPKdudagd2hLKR5"

	// Include the noscript tags in the generated captcha
	includeNoScript = true
}

mailhide {
    // Generated by the Mailhide service
    publicKey  = "6Lc6dPgSAAAAAPOwGa9-CmSE_HdprJ-ci5aflPWJ"
    privateKey = "6Lc6dPgSAAAAAJSUxs8xxqmO-KPKdudagd2hLKR5"
}

environments {
  development {
    recaptcha {
      // Set to false to disable the display of captcha
      enabled = true

      // Communicate using HTTPS
      useSecureAPI = true
    }
  }
  production {
    recaptcha {
      // Set to false to disable the display of captcha
      enabled = true

      // Communicate using HTTPS
      useSecureAPI = true
    }
  }
}